"""
한국 대학 영문명 → 한국명 매핑
universities.json에 name_ko 필드 추가
"""

import json
from pathlib import Path

# 영문명 → 한국명 매핑
KO_NAMES: dict[str, str] = {
    "Seoul National University": "서울대학교",
    "Yonsei University": "연세대학교",
    "Sungkyunkwan University": "성균관대학교",
    "Korea University": "고려대학교",
    "Korea Advanced Institute of Science and Technology": "한국과학기술원(KAIST)",
    "Hanyang University": "한양대학교",
    "Kyung Hee University": "경희대학교",
    "Kyungpook National University": "경북대학교",
    "Pusan National University": "부산대학교",
    "University of Ulsan": "울산대학교",
    "Pohang University of Science and Technology": "포항공과대학교(POSTECH)",
    "Chungnam National University": "충남대학교",
    "Catholic University of Korea": "가톨릭대학교",
    "Chonnam National University": "전남대학교",
    "Jeonbuk National University": "전북대학교",
    "Chung-Ang University": "중앙대학교",
    "Inha University": "인하대학교",
    "Ajou University": "아주대학교",
    "Ulsan College": "울산과학대학교",
    "Ewha Womans University": "이화여자대학교",
    "Yeungnam University": "영남대학교",
    "Konkuk University": "건국대학교",
    "Chungbuk National University": "충북대학교",
    "Gyeongsang National University": "경상국립대학교",
    "Kangwon National University": "강원대학교",
    "Sejong University": "세종대학교",
    "Dongguk University": "동국대학교",
    "Korea University of Science and Technology": "한국과학기술연합대학원대학교(UST)",
    "Pukyong National University": "부경대학교",
    "Gachon University": "가천대학교",
    "Gwangju Institute of Science and Technology": "광주과학기술원(GIST)",
    "Dankook University": "단국대학교",
    "Ulsan National Institute of Science and Technology": "울산과학기술원(UNIST)",
    "Hallym University": "한림대학교",
    "Chosun University": "조선대학교",
    "Soonchunhyang University": "순천향대학교",
    "Keimyung University": "계명대학교",
    "Sogang University": "서강대학교",
    "Jeju National University": "제주대학교",
    "Dong-A University": "동아대학교",
    "Seoul National University of Science and Technology": "서울과학기술대학교",
    "Wonkwang University": "원광대학교",
    "University of Seoul": "서울시립대학교",
    "Incheon National University": "인천대학교",
    "Inje University": "인제대학교",
    "Soongsil University": "숭실대학교",
    "CHA University": "차의과학대학교",
    "Kookmin University": "국민대학교",
    "Kwangwoon University": "광운대학교",
    "Kongju National University": "공주대학교",
    "Hongik University": "홍익대학교",
    "Changwon National University": "창원대학교",
    "Daegu Catholic University": "대구가톨릭대학교",
    "Eulji University": "을지대학교",
    "Anyang University": "안양대학교",
    "Sunchon National University": "순천대학교",
    "Daegu Gyeongbuk Institute of Science and Technology": "대구경북과학기술원(DGIST)",
    "Hankuk University of Foreign Studies": "한국외국어대학교",
    "Myongji University": "명지대학교",
    "Kyonggi University": "경기대학교",
    "Sookmyung Women's University": "숙명여자대학교",
    "Kunsan National University": "군산대학교",
    "Duksung Women's University": "덕성여자대학교",
    "Semyung University": "세명대학교",
    "Daejeon University": "대전대학교",
    "Korea Aerospace University": "한국항공대학교",
    "Hanbat National University": "한밭대학교",
    "Kumoh National Institute of Technology": "금오공과대학교",
    "Pai Chai University": "배재대학교",
    "Andong National University": "안동대학교",
    "Hanseo University": "한서대학교",
    "Woosong University": "우송대학교",
    "Seoul Women's University": "서울여자대학교",
    "Dongseo University": "동서대학교",
    "Korea National University of Transportation": "한국교통대학교",
    "Mokpo National University": "목포대학교",
    "Gyeongnam National University of Science and Technology": "경남과학기술대학교",
    "Hanshin University": "한신대학교",
    "Honam University": "호남대학교",
    "Joongbu University": "중부대학교",
    "Hallym Polytechnic University": "한림성심대학교",
    "Catholic University of Pusan": "부산가톨릭대학교",
    "Korea National Open University": "한국방송통신대학교",
    "Cheju Halla University": "제주한라대학교",
    "Baekseok University": "백석대학교",
    "Korea National Sport University": "한국체육대학교",
    "Korean Academy of Science and Technology": "한국과학기술한림원",
    "Seowon University": "서원대학교",
    "Seokyeong University": "서경대학교",
    "Jungwon University": "중원대학교",
    "Mokpo National Maritime University": "목포해양대학교",
    "Youngsan University": "영산대학교",
    "Korean Council for University Education": "한국대학교육협의회",
    "Ghent University Global Campus": "겐트대학교 글로벌캠퍼스",
    "Gongju National University of Education": "공주교육대학교",
    "Korea Military Academy": "육군사관학교",
    "Chinju National University of Education": "진주교육대학교",
    "Seoul School of Integrated Sciences and Technologies": "아이에스티(aSSIST)",
    "Taegu Science University": "대구과학대학교",
    "Baewha Women's University": "배화여자대학교",
    "Daegu Health College": "대구보건대학교",
    "Nambu University": "남부대학교",
    "Chungwoon University": "청운대학교",
    "Sehan University": "세한대학교",
    "Chung Cheong University": "충청대학교",
    "Gwangju Health University": "광주보건대학교",
    "Kyung Hee Cyber University": "경희사이버대학교",
    "Busan National University of Education": "부산교육대학교",
    "Shinhan University": "신한대학교",
    "Korea University of International Studies": "한국외국어대학교",
    "Yuhan University": "유한대학교",
    "Dongyang University": "동양대학교",
    "SUNY Korea": "스토니브룩대학교 한국캠퍼스",
    "Gangneung–Wonju National University": "강릉원주대학교",
    "Dong-Eui University": "동의대학교",
    "Daegu University": "대구대학교",
    "Korea Maritime and Ocean University": "한국해양대학교",
    "Catholic Kwandong University": "가톨릭관동대학교",
    "Yong In University": "용인대학교",
    "Hoseo University": "호서대학교",
    "Konyang University": "건양대학교",
    "Sangmyung University": "상명대학교",
    "Hannam University": "한남대학교",
    "Hankyong National University": "한경국립대학교",
    "Sun Moon University": "선문대학교",
    "Korea University of Technology and Education": "한국기술교육대학교",
    "Kosin University": "고신대학교",
    "Kyungnam University": "경남대학교",
    "Seoul National University of Education": "서울교육대학교",
    "Jeonju University": "전주대학교",
    "Cheongju University": "청주대학교",
    "University of Suwon": "수원대학교",
    "Sungshin Women's University": "성신여자대학교",
    "Kyungsung University": "경성대학교",
    "Sahmyook University": "삼육대학교",
    "Sangji University": "상지대학교",
    "Woosuk University": "우석대학교",
    "Silla University": "신라대학교",
    "Daegu Haany University": "대구한의대학교",
    "Daejin University": "대진대학교",
    "Tongmyong University": "동명대학교",
    "Dongduk Women's University": "동덕여자대학교",
    "Hansung University": "한성대학교",
    "Korea National University of Education": "한국교원대학교",
    "Mokwon University": "목원대학교",
    "Handong Global University": "한동대학교",
    "Kangnam University": "강남대학교",
    "Gwangju University": "광주대학교",
    "Busan University of Foreign Studies": "부산외국어대학교",
    "Korea Nazarene University": "나사렛대학교",
    "Gimcheon University": "김천대학교",
    "Gyeongin National University of Education": "경인교육대학교",
    "Daegu National University of Education": "대구교육대학교",
    "Changshin University": "창신대학교",
    "Hyupsung University": "협성대학교",
    "Sungkonghoe University": "성공회대학교",
    "Korea National University of Arts": "한국예술종합학교",
    "Chuncheon National University of Education": "춘천교육대학교",
    "Jeonju National University of Education": "전주교육대학교",
    "KDI School of Public Policy and Management": "KDI국제정책대학원대학교",
    "Kyungil University": "경일대학교",
    "Namseoul University": "남서울대학교",
    "Kyungdong University": "경동대학교",
    "Seonam University": "서남대학교",
    "Gyeongju University": "경주대학교",
    "Halla University": "한라대학교",
    "Pyeongtaek University": "평택대학교",
    "Youngdong University": "영동대학교",
    "Uiduk University": "위덕대학교",
    "Daejeon University": "대전대학교",
    "Korea Aerospace University": "한국항공대학교",
    "Hanbat National University": "한밭대학교",
    "Kumoh National Institute of Technology": "금오공과대학교",
    "Pai Chai University": "배재대학교",
    "Andong National University": "안동대학교",
    "Hanseo University": "한서대학교",
    "Woosong University": "우송대학교",
    "Seoul Women's University": "서울여자대학교",
    "Dongseo University": "동서대학교",
    "Korea National University of Transportation": "한국교통대학교",
    "Mokpo National University": "목포대학교",
    "Bucheon University": "부천대학교",
    "Mokpo National Maritime University": "목포해양대학교",
    "Seoul Media Institute of Technology": "서울미디어대학원대학교",
    "Far East University": "극동대학교",
    "Yong-in Songdam College": "용인송담대학교",
    "Sungkyul University": "성결대학교",
    "WonKwang Health Science University": "원광보건대학교",
    "Inha Technical College": "인하공업전문대학",
}


def main():
    uni_file = Path("data/universities.json")
    data = json.loads(uni_file.read_text(encoding="utf-8"))

    matched = 0
    for u in data["universities"]:
        ko = KO_NAMES.get(u["name"])
        if ko:
            u["name_ko"] = ko
            matched += 1
        else:
            u["name_ko"] = ""

    uni_file.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"완료: {matched}/{len(data['universities'])}개 한국명 매칭")

    # 미매칭 목록 출력
    unmatched = [u["name"] for u in data["universities"] if not u["name_ko"]]
    if unmatched:
        print(f"\n미매칭 ({len(unmatched)}개):")
        for n in unmatched[:20]:
            print(f"  - {n}")


if __name__ == "__main__":
    main()
